# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.hostname = "opencti-server"

  # Network configuration
  config.vm.network "private_network", ip: "192.168.56.30"
  
  # Port forwarding for the Web UI
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.provider "vmware_desktop" do |v|
    v.vmx["displayName"] = "OpenCTI-Platform"
    v.memory = 8192 # OpenCTI requires at least 8GB to run all containers reliably
    v.cpus = 4
  end

  # Provisioning script
  config.vm.provision "shell", path: "setup_opencti.sh"
end